### ISSUE TITLE
Text overlapping/UI enhancements

### ISSUE THREAD

**Issue by caco3** [haverland/collectmeteranalog#2]
Nice tool!

Its quite laggy on my maschine, maybe thats normal because of the processing when jumping to the next image?
Also incrementing/decrementing is quite slow. For me it would be more efficient to enter the value instead of pressing up/down all the time, what do you think?

Also the numbers around are hard to read:
![grafik](https://user-images.githubusercontent.com/1783586/185762533-dbdf316d-50ae-424f-a3d4-50bd8a4c88da.png)
I simply would make them smaller, maybe rotate the slightly or only show every 2nd 3th number and simply ticks between.

**Comment by haverland** [comment]
It fast on my machine, but I have a powerful laptop.

you can use + , - for up down and left/right cursor for previous / update. This is really fast for me. 

You maximize the window? What's you screen resolution?

**Comment by caco3** [comment]
Yes, I use full screen, 1920x1080.

I am extending your UI to also support `+/-1.0`, I will create a Pull request soon.

**Comment by haverland** [comment]
I've added --model=off for not using predictions

**Comment by haverland** [comment]
I'am wondering about the big size. Looks here
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/412645/185764077-15ef77a2-36c8-4235-8f13-43d25ab5c0da.png">

**Comment by caco3** [comment]
> I've added --model=off for not using predictions

Nice, that helps a lot! (I have a i5-4300U CPU @ 1.90GHz so it should be good enough).

> I'am wondering about the big size.

Maybe thats an issue of my GUI config on Linux

**Comment by haverland** [comment]
LOL. It's the same model we use on the esp32-cam :-)

**Comment by caco3** [comment]
What do you think about https://github.com/haverland/collectmeteranalog/pull/3 ?

**Comment by haverland** [comment]
Thanks. I've added an option --ticksteps to able to change it.
The additional +1/-1 are helpful too
