### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by caco3** [haverland/collectmeteranalog#7]
For me, the changing the picture or the value takes around 2 seconds on a Linux system with an i5-4300U CPU @ 1.90GHz.
Similar performance I see also on a more powerful system.

I would like to know how it responds on other systems to see if it is only my setup.

**Comment by haverland** [comment]
Mac M1 less than 0.5s for a change.

**Comment by caco3** [comment]
Well, those 2 maschines are definitely different league :) https://www.cpu-monkey.com/en/compare_cpu-apple_m1-1804-vs-intel_core_i5_4300u-302

Nevertheless, my maschine is still ok and anything else I usually do is not lagging as much.

I digged into it more now and figured out that the core performance breaker is the grid.
Would it be ok for you when we disable the grid (uncomment the line with `ax2.grid(False)`)?
![grafik](https://user-images.githubusercontent.com/1783586/185809225-355eb045-aec4-497d-8898-eb8960b1f4e8.png)


Without a grid, its MUCH faster, almost not lagging anymore. 
Also I see no need for a grid as the user doesnt really need to know the angle at all.

**Comment by haverland** [comment]
Could you try the last changes. The Clickevent on the fig made an issue together with the button events.

If it is not fast, if you use keys it is faster?

The grid is really needed, if you want label an accuracy of +/- 0.1. Not the angle is relevant here at all. Most of the images are sheared or moved. In your picture the green line shoes more a 0.2 than a 0.3. Look at the dashes of 0.0 and 0.5

**Comment by caco3** [comment]
replaced by change mentioned in https://github.com/haverland/collectmeteranalog/issues/9#issuecomment-1222520555
